# Setup
title:               Jack Sparrow
tagline:             'A Jekyll theme'
description:         'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 https://profile.1tyu.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Jack Sparrow
  url:               https://profile.1tyu.com
  email:             yusais_life@qq.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
