# Setup
title:               Jack Sparrow
tagline:             'A Jekyll theme'
description:         '工作经历'
url:                 https://profile.1tyu.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Jack Sparrow
  url:               https://profile.1tyu.com
  email:             yusais_life@qq.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             0.1
google_analytics_id: #UA-XXXX-Y
